symbol.return
code.close
sharpen.data
input[1][2]
hidden[3][4]
output[5][6]
cpuClass.action
cpu.action
cpu.input[1][2]
cpu.hidden[3][4]
cpu.output[5][6]
cpu.performance.optimizing.input[1][2]
cpu.performance.optimizing.hidden[3][4]
cpu.performance.optimizing.output[5][6]
cpu.unlimited.performance.input[1][2]
cpu.unlimited.performance.hidden[3][4]
cpu.unlimited.performance.output[5][6]
cpu.disable.ping.input[1][2]
cpu.disable.ping.hidden[3][4]
cpu.disable.ping.output[5][6]
